name: Build Specific Commit

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The commit SHA to checkout and build'
        required: true

jobs:
  build_commit:
    runs-on: [self-hosted, linux]  # Specifies a self-hosted runner

    steps:
      - name: Checkout the repository at SHA
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.sha }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Parse `settings.gradle` for wilderworkspace version
        id: parse_version
        run: |
          # Parse settings.gradle for the version of wilderworkspace
          VERSION=$(grep -oP "useModule\('com\.wildermods:wilderworkspace:(.*?)'\)" settings.gradle | sed -E "s/useModule\('com\.wildermods:wilderworkspace:(.*)'\)/\1/")
          echo "WILDERWORKSPACE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download WilderWorkspace JAR from GitHub
        run: |
          # Create libs directory if it doesn't exist
          mkdir -p libs
          
          # Construct the GitHub release URL based on the version
          RELEASE_URL="https://github.com/WilderForge/WilderWorkspace/releases/download/${{ env.WILDERWORKSPACE_VERSION }}/wilderworkspace-${{ env.WILDERWORKSPACE_VERSION }}.jar"
          
          # Add ?raw=true to ensure we download the raw file
          RAW_URL="${RELEASE_URL}?raw=true"
          
          # Echo the URL for debugging purposes
          echo "Downloading from URL: $RAW_URL"
          
          # Download the wilderworkspace JAR using curl
          curl -L -o libs/wilderworkspace-${{ env.WILDERWORKSPACE_VERSION }}.jar $RAW_URL
          
          # Verify download success
          ls -lh libs

      - name: Clear Game Files
        run: ./gradlew clearLocalRuntime

      - name: Setup Decompiled Workspace
        run: ./gradlew setupDecompWorkspace

      - name: Build With Gradle
        run: ./gradlew build
