name: Remote Build Status

on:
  workflow_run:
    workflows: ["Validate Approval"]
    types:
      - requested

jobs:
  checkApprovalJob:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Validate Approval workflow to complete
        id: wait_for_validation
        run: |
          echo "Waiting for Validate Approval workflow to complete..."
          
          # Define the API URL to get workflow run status
          WORKFLOW_RUN_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"

          # Loop to check the status of the workflow run
          while true; do
            # Make an API request to get the status of the workflow run
            response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $WORKFLOW_RUN_URL)

            # Extract the status and conclusion from the API response
            status=$(echo "$response" | jq -r '.status')
            conclusion=$(echo "$response" | jq -r '.conclusion')

            if [[ "$status" == "completed" ]]; then
              echo "Validate Approval workflow completed with conclusion: $conclusion"
              break
            else
              echo "Validate Approval workflow is still in progress..."
              echo "status: $status"
              echo "conclusion: $conclusion"
              sleep 10  # Sleep for 10 seconds and retry
            fi
          done
          echo "status=$status" >> $GITHUB_OUTPUT
          echo "conclusion=$conclusion" >> $GITHUB_OUTPUT
      - name: Checking Validation Job
        run: |
          # Access the outputs from the previous step
          status=${{ steps.wait_for_validation.outputs.status }}
          conclusion=${{ steps.wait_for_validation.outputs.conclusion }}

          echo "Status: $status"
          echo "Conclusion: $conclusion"

          if [ "$conclusion" == "success" ]; then
            exit 0;
          else
            echo "Approval validation failed - status: $status - conclusion: $concluion"
            exit 1;
          fi
