name: Remote Build Status

on:
  workflow_run:
    workflows: ["Validate Approval"]
    types:
      - completed

jobs:
  checkApprovalJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Validation Job
        run: |
          # Extract status and conclusion from the workflow_run context
          status="${{ github.event.workflow_run.status }}"
          conclusion="${{ github.event.workflow_run.conclusion }}"

          echo "Status: $status"
          echo "Conclusion: $conclusion"

          # Check if the validation succeeded or failed
          if [ "$conclusion" == "success" ]; then
            echo "Approval validation passed."
            exit 0
          else
            echo "Approval validation failed - status: $status - conclusion: $conclusion"
            exit 1
          fi
