name: Remote Build Status

on:
  workflow_run:
    workflows: ["Validate Approval"]
    types:
      - requested

jobs:
  checkApprovalJob:
    runs-on: ubuntu-latest
    steps:
      - name: Set PR Status to Pending
        id: set_pending_status
        run: |
          PR_URL=$(echo "${{ github.event.workflow_run.pull_requests }}" | jq -r '.[0].url')
          HEAD_SHA=$(echo "${{ github.event.workflow_run.head_sha }}")

          if [ -z "$PR_URL" ] || [ "$PR_URL" == "null" ]; then
            echo "No pull request associated with this workflow run. Exiting."
            exit 1
          fi

          # Post pending status to the pull request commit
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"state\": \"pending\",
              \"description\": \"Remote Build Status is running.\",
              \"context\": \"Remote Build Status\"
            }" \
            "https://api.github.com/repos/${{ github.repository }}/statuses/$HEAD_SHA"
      - name: Wait for Validate Approval workflow to complete
        id: wait_for_validation
        run: |
          echo "Waiting for Validate Approval workflow to complete..."
          
          # Define the API URL to get workflow run status
          WORKFLOW_RUN_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"

          max_attempts=60
          attempt=0

          # Loop to check the status of the workflow run
          while true; do
            # Make an API request to get the status of the workflow run
            response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $WORKFLOW_RUN_URL)

            # Extract the status and conclusion from the API response
            status=$(echo "$response" | jq -r '.status')
            conclusion=$(echo "$response" | jq -r '.conclusion')

            if [[ "$status" == "completed" ]]; then
              echo "Validate Approval workflow completed with conclusion: $conclusion"
              break
            elif [[ $attempt -ge $max_attempts ]]; then
              echo "Reached maximum number of attempts ($max_attempts). Exiting."
              status="timed_out"
              conclusion="failure"
              break
            else
              echo "Validate Approval workflow is still in progress..."
              echo "Attempt $attempt/$max_attempts"
              echo "status: $status"
              echo "conclusion: $conclusion"
              sleep 10  # Sleep for 10 seconds and retry
            fi
          done
          echo "status=$status" >> $GITHUB_OUTPUT
          echo "conclusion=$conclusion" >> $GITHUB_OUTPUT
      - name: Checking Validation Job
        run: |
          # Access the outputs from the previous step
          status=${{ steps.wait_for_validation.outputs.status }}
          conclusion=${{ steps.wait_for_validation.outputs.conclusion }}

          echo "Status: $status"
          echo "Conclusion: $conclusion"

          if [ "$conclusion" == "success" ]; then
            exit 0;
          else
            echo "Approval validation failed - status: $status - conclusion: $conclusion"
            exit 1;
          fi
      - name: Update PR Status
        if: ${{ always() }} # Always run to ensure a status is set even on failure
        run: |
          PR_URL=$(echo "${{ github.event.workflow_run.pull_requests }}" | jq -r '.[0].url')
          HEAD_SHA=$(echo "${{ github.event.workflow_run.head_sha }}")

          if [ -z "$PR_URL" ] || [ "$PR_URL" == "null" ]; then
            echo "No pull request associated with this workflow run. Exiting."
            exit 1
          fi

          STATUS="in_progress"
          if [ "${{ steps.wait_for_validation.outputs.conclusion }}" == "success" ]; then
            STATUS="success"
          elif [ "${{ steps.wait_for_validation.outputs.conclusion }}" == "failure" ]; then
            STATUS="failure"
          fi

          # Post status to the pull request commit
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"state\": \"$STATUS\",
              \"description\": \"Remote Build Status workflow completed.\",
              \"context\": \"Remote Build Status\"
            }" \
            "https://api.github.com/repos/${{ github.repository }}/statuses/$HEAD_SHA"
