on:
  pull_request_review:
    types: [submitted]

jobs:
  approve_and_run:
    runs-on: ubuntu-latest
    if: |
      (
        github.event.review.state == 'approved' &&
        github.event.review.user.login == 'Gamebuster19901'
      ) ||
      (
        github.event.pull_request != null &&
        github.event.sender.login == 'Gamebuster19901' &&
        github.event.pull_request.user.login == 'Gamebuster19901' &&
        startsWith(github.event.review.body, 'approved') &&
        github.event.pull_request.head.sha == github.event.review.commit_id
      )
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # Checkout the PR's head branch
      - name: Validate Commit SHA
        run: |
          if [ "${{ github.event.pull_request.head.sha }}" != "${{ github.sha }}" ]; then
            echo "Commit SHA does not match approved version. Exiting."
            exit 1
          fi
      - name: Running
        run: echo "Running approved workflow!"
