on:
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  approve_and_run:
    runs-on: ubuntu-latest
    if: |
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved' &&
        github.event.review.user.login == 'your-username'
      ) ||
      (
        github.event_name == 'issue_comment' &&
        github.event.comment.user.login == 'your-username' &&
        to_lowercase(github.event.comment.body) == 'approved' &&
        length(trim(github.event.comment.body)) == 8 &&
        github.event.issue.pull_request != null &&
        github.event.issue.user.login == 'your-username'
      )
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate Commit SHA
        run: |
          if [ "${{ github.event.pull_request.head.sha }}" != "${{ github.sha }}" ]; then
            echo "Commit SHA does not match approved version. Exiting."
            exit 1
          fi
      - name: Running
        run: echo "Running approved workflow!"
