name: Validate Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  approve_and_run:
    runs-on: ubuntu-latest
    outputs:
      pr_sha: ${{ steps.approve_sha.outputs.approved_sha }}
    if: |
      (
        github.event.review.state == 'approved' &&
        github.event.review.user.login == 'Gamebuster19901'
      ) ||
      (
        github.event.pull_request != null &&
        github.event.sender.login == 'Gamebuster19901' &&
        github.event.pull_request.user.login == 'Gamebuster19901' &&
        startsWith(github.event.review.body, 'approved')
      )
    steps:
      - name: Validate Commit SHA
        run: |
          if [ "${{ github.event.pull_request.head.sha }}" != "${{ github.event.review.commit_id }}" ]; then
            echo "Latest SHA in PR does not match approved version. Exiting."
            exit 1
          fi
      - name: Setting Approved SHA
        id: "approve_sha"
        run: echo "approved_sha=${{ github.event.review.commit_id }}" >> $GITHUB_ENV
