name: Validate Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  approve_and_run:
    runs-on: ubuntu-latest
    outputs:
      pr_sha: ${{ steps.approve_sha.outputs.approved_sha }}
    if: |
      (
        github.event.review.state == 'approved' &&
        github.event.review.user.login == 'Gamebuster19901'
      ) ||
      (
        github.event.pull_request != null &&
        github.event.sender.login == 'Gamebuster19901' &&
        github.event.pull_request.user.login == 'Gamebuster19901' &&
        startsWith(github.event.review.body, 'approved')
      )
    steps:
      - name: Validate Commit SHA
        id: "validate_sha"
        run: |
          if [ "${{ github.event.pull_request.head.sha }}" != "${{ github.event.review.commit_id }}" ]; then
            echo "Latest SHA in PR does not match approved version. Exiting."
            exit 1
          fi

      - name: Setting Approved SHA
        id: "approve_sha"
        run: echo "approved_sha=${{ github.event.review.commit_id }}" >> $GITHUB_ENV

      - name: Post Status Check
        if: always()  # Ensures this step always runs
        run: |
          # Check the outcome of the validation step
          if [ "${{ steps.validate_sha.outcome }}" == "success" ]; then
            STATUS="success"
            DESCRIPTION="Approval validated for commit"
          else
            STATUS="failure"
            DESCRIPTION="Approval validation: failed"
          fi

          CONTEXT="Approval Validation"
          APPROVED_SHA="${{ steps.approve_sha.outputs.approved_sha }}"

          # Post the status using GitHub API
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"state\": \"$STATUS\",
              \"description\": \"$DESCRIPTION\",
              \"context\": \"$CONTEXT\"
            }" \
            "https://api.github.com/repos/${{ github.repository }}/statuses/$APPROVED_SHA"
